FIX: Update camera.py
BUG: AttributeError: 'dict' object has no attribute 'iteritems'.

iteritems() has been removed in recent Python releases. 
Replace iteritems() to items()